---
abstract: 'Install all Perinci:: modules'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Perinci
requires:
  Perinci: 0
  Perinci::Examples: 0
  Riap: 0
  Rinci: 0
resources:
  homepage: http://search.cpan.org/dist/Task-Perinci/
  repository: http://github.com/sharyanto/perl-Task-Perinci
version: 0.03
