---
abstract: 'Install all Perinci:: modules'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0.88
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Perinci
requires:
  Perinci: 0
  Perinci::Access: 0
  Perinci::Access::Base: 0
  Perinci::Access::HTTP::Client: 0
  Perinci::Access::HTTP::Server: 0
  Perinci::Access::Perl: 0
  Perinci::Access::Simple::Client: 0
  Perinci::Access::Simple::Server: 0
  Perinci::BashComplete: 0
  Perinci::CmdLine: 0
  Perinci::Easy: 0
  Perinci::Examples: 0
  Perinci::Examples::Bin: 0
  Perinci::Exporter: 0
  Perinci::Gen::ForModule: 0
  Perinci::Object: 0
  Perinci::Result::Format: 0
  Perinci::Sub::ConvertArgs::Array: 0
  Perinci::Sub::Dep::pm: 0
  Perinci::Sub::DepChecker: 0
  Perinci::Sub::Gen: 0
  Perinci::Sub::Gen::AccessTable: 0
  Perinci::Sub::Gen::AccessTable::DBI: 0
  Perinci::Sub::GetArgs::Argv: 0
  Perinci::Sub::GetArgs::Array: 0
  Perinci::Sub::Property::curry: 0
  Perinci::Sub::Property::dies_on_error: 0
  Perinci::Sub::Property::drops_privilege: 0
  Perinci::Sub::Property::retry: 0
  Perinci::Sub::Property::timeout: 0
  Perinci::Sub::PropertyUtil: 0
  Perinci::Sub::Wrapper: 0
  Perinci::To::HTML: 0
  Perinci::To::POD: 0
  Perinci::To::Text: 0
  Perinci::Tx::Manager: 0
  Perinci::Use: 0
  Perinci::Util: 0
  Perinci::Web: 0
  Pod::Weaver::Plugin::Perinci: 0
  Riap: 0
  Rinci: 0
  Rinci::Schema: 0
resources:
  homepage: http://search.cpan.org/dist/Task-Perinci/
  repository: http://github.com/sharyanto/perl-Task-Perinci
version: 0.12
